build:
	iverilog -o Simulation/decoder1to2withEnable.executable Source_code/decoder1to2withEnable_tb.v

simulation:
	Simulation/decoder1to2withEnable.executable
wave:
	gtkwave Simulation/decoder1to2withEnable.vcd
