build:
	cd ../Source_code && iverilog -o ../GNU_toolchain/Simulation/multiplexer2to1_tb.executable multiplexer2to1_tb.v
	
simulation:
	Simulation/multiplexer2to1_tb.executable
wave:
	gtkwave Simulation/multiplexer2to1_tb.vcd
