build:
	iverilog -o Simulation/decoder2to4withEnable.executable Source_code/decoder2to4withEnable_tb.v

simulation:
	Simulation/decoder2to4withEnable.executable
wave:
	gtkwave Simulation/decoder2to4withEnable.vcd
