build:
	iverilog -o Simulation/multiplexer2to1_tb.executable Source_code/multiplexer2to1/multiplexer2to1.v Source_code/multiplexer2to1_tb.v
simulation:
	Simulation/multiplexer2to1_tb.executable
wave:
	gtkwave Simulation/multiplexer2to1_tb.vcd
